version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    ports:
      - '27018:27018'
  redis:
    image: redis
    ports:
      - '6379:6379'
